# Generated by Django 5.2.3 on 2025-08-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(help_text='Связь вопроса с тестом', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.test', verbose_name='Тест'),
        ),
    ]
